### ISSUE TITLE
[coc.nvim]: Slow "BufWritePre" handler detected s

### ISSUE THREAD

**Issue by marryton007** [Martins3/My-Linux-Config#115]
- [x] **Describe the bug**
When saving a file, it takes a long time and issues error messages.

```sh
[coc.nvim]: glob error [Error: EACCES: permission denied, scandir '/opt/sdk/rock/rk-android11/Source/out/target/product/rk3568/root/d/scala'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/opt/sdk/rock/rk-android11/Source/out/target/product/rk3568/root/d/scala'
}
[coc.nvim]: Slow "BufWritePre" handler detected s
    at sk.on (/home/jiaxi/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:58:4295)
    at bp.attach (/home/jiaxi/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:177:4856)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async vR.init (/home/jiaxi/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:198:621)
    at async _b.init (/home/jiaxi/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:281:45514)
"rk3568/rk3568.mk" 50L, 1881B written
```

- [x] **ccls --version**
```sh
jiaxi in share/nvim/site ❯ ccls --version
Ubuntu ccls version 0.20220729-4-g8bc39595
clang version 15.0.7
```

- [x] **nvim --version**
```sh
jiaxi in share/nvim/site ❯ nvim --version
NVIM v0.8.0-v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jiaxi@lenovo

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- [x] **Operating System**
ubuntu 20.04 server

- [x] **CocInfo**
```sh
## versions

vim version: NVIM v0.8.0-v0.8.0
node version: v16.18.1
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/jiaxi/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2023-03-07T10:36:05.300 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2023-03-07T10:36:05.301 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2023-03-07T10:36:05.301 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2023-03-07T10:36:05.301 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2023-03-07T10:36:05.665 INFO (pid:73526) [extension:coc-git] - Looking for git in: git
2023-03-07T10:36:05.726 INFO (pid:73526) [plugin] - coc.nvim initialized with node: v16.18.1 after 502
2023-03-07T10:36:05.727 INFO (pid:73526) [attach] - receive notification: highlight []
2023-03-07T10:36:05.782 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2023-03-07T10:36:05.783 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2023-03-07T10:36:05.783 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2023-03-07T10:36:05.783 INFO (pid:73526) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2023-03-07T10:36:09.865 INFO (pid:73526) [attach] - receive notification: showInfo []
```

- [x] **checkhealth screenshot**
```sh
coc: health#coc#check
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed
  - OK: Javascript bundle build/index.js found
  - OK: Service started

floaterm: health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.8.0-v0.8.0
  - INFO: Plugin: ca44a13


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

gitmessenger: health#gitmessenger#check
========================================================================
  - OK: +job is available to execute Git command
  - OK: Git command `git` is available: git version 2.39.2
  - OK: Floating window is available for popup window

gitsigns: require("gitsigns.health").check()
========================================================================
  - OK: git version 2.39.2

hydra: require("hydra.health").check()
========================================================================
## Hydra: Checking settings
  - OK:             `timeoutlen` (value: 1000) is set to a good value.

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

mkdp: health#mkdp#check
========================================================================
  - INFO: Platform: linux
  - INFO: Nvim Version: NVIM v0.8.0-v0.8.0
  - INFO: Node version: v16.18.1

  - INFO: Script: /home/jiaxi/.local/share/nvim/site/pack/packer/start/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/2'
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.18.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.4.0-144-generic",
  sysname = "Linux",
  version = "#161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023"
}

## Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - java                ✓ ✓ . ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - nix                 ✓ ✓ ✓ . ✓
  - org                 . . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scala               ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.10
  - INFO: pynvim version: 0.4.3
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 7

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.9.0

## Node.js provider (optional)
  - INFO: Node.js: v16.18.1
  - INFO: Nvim node.js host: /home/jiaxi/.nvm/versions/node/v16.18.1/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev 7ec2fd51ba)
  - OK: fd: found fd 7.5.0

## ===== Installed extensions =====

## Telescope Extension: `bookmarks`
  - INFO: No healthcheck provided

## Telescope Extension: `emoji`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured

## Telescope Extension: `heading`
  - INFO: No healthcheck provided

## Telescope Extension: `neoclip`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/jiaxi/.local/state/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cpp: ABI version 14
  - OK: Loaded parser for go: ABI version 14
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for java: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for org: ABI version 14
  - OK: Loaded parser for python: ABI version 14
  - OK: Loaded parser for rust: ABI version 14
  - OK: Loaded parser for scala: ABI version 14
  - OK: Loaded parser for vim: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"f"**
  - INFO: rhs: ` `
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>Commentary`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"yS"**
  - INFO: rhs: `<Plug>(nvim-surround-normal-line)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"ys"**
  - INFO: rhs: `<Plug>(nvim-surround-normal)`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>d"**
  - INFO: old rhs: `"+d`
  - INFO: new rhs: `<cmd>Telescope coc workspace_diagnostics<cr>`
```

**Comment by Martins3** [comment]
这个是最近更新之后有的吗？

**Comment by marryton007** [comment]
```git
commit 73366eab8066d0bfa4170a8e7e9644c6ed707e49 (HEAD -> master, origin/master, origin/HEAD)
Merge: beaa6b2 33d6c48
Author: Martin Three <hubachelar@gmail.com>
Date:   Sat Feb 18 11:35:43 2023 +0800

    Merge pull request #97 from Martins3/nov

commit 33d6c488c007f07e6cbc94831503e834469ecce0
Author: Martins3 <hubachelar@gmail.com>
Date:   Sat Feb 18 11:28:44 2023 +0800

    docs: nvim: separate changelog into a standalone file
```
最近有同步过。

**Comment by marryton007** [comment]
[nvim-config.patch](https://github.com/Martins3/My-Linux-Config/files/10905043/nvim-config.patch)

改了些配置。

**Comment by marryton007** [comment]
我刚才试了下在其他的目录里编辑文件，打开文件的时候就出现了scandir报没有权限的问题，但保存的时候很快，没有卡顿。

不知道是不是与目录里的内容有关系，前面那个出错的目录里面是AOSP的源码。

**Comment by Martins3** [comment]
个人感觉和
```
/opt/sdk/rock/rk-android11/Source/out/target/product/rk3568/root/d/scala
```
中的内容有关，你可以 cd 到里面看看，是不是权限不对

**Comment by marryton007** [comment]
```sh
jiaxi in product/rk3568_ehome_ba200_a1/root on  merge-4g ❯ pwd
/opt/sdk/rock/rk-android11/Source/out/target/product/rk3568/root
jiaxi in product/rk3568_ehome_ba200_a1/root on  merge-4g ❯ ls -l
total 88
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 acct
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 apex
lrwxrwxrwx 1 jiaxi jiaxi   11 Mar  3 10:58 bin -> /system/bin
lrwxrwxrwx 1 jiaxi jiaxi   50 Mar  3 10:58 bugreports -> /data/user_de/0/com.android.shell/files/bugreports
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 cache
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 config
lrwxrwxrwx 1 jiaxi jiaxi   17 Mar  3 10:58 d -> /sys/kernel/debug
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 data
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 data_mirror
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 debug_ramdisk
lrwxrwxrwx 1 jiaxi jiaxi   23 Mar  3 10:58 default.prop -> system/etc/prop.default
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 dev
lrwxrwxrwx 1 jiaxi jiaxi   11 Mar  3 10:58 etc -> /system/etc
lrwxrwxrwx 1 jiaxi jiaxi   16 Mar  3 10:58 init -> /system/bin/init
-rw-rw-r-- 1 jiaxi jiaxi 2231 Mar  3 10:58 init.environ.rc
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 linkerconfig
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 metadata
drwxrwxr-x 3 jiaxi jiaxi 4096 Mar  3 10:57 mnt
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 odm
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 oem
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 proc
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 product
drwxrwxr-x 3 jiaxi jiaxi 4096 Mar  3 10:57 res
lrwxrwxrwx 1 jiaxi jiaxi   21 Mar  3 10:58 sdcard -> /storage/self/primary
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 storage
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 sys
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 system
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 system_ext
drwxrwxr-x 2 jiaxi jiaxi 4096 Mar  3 10:58 vendor
jiaxi in product/rk3568_ehome_ba200_a1/root on  merge-4g ❯
```

**Comment by marryton007** [comment]
scala 这个目录很奇怪，所有报错的地方都没有这个目录，却老是这个目录报错。

**Comment by Martins3** [comment]
感觉应该是配置出现了问题，我今晚尝试复现一下

**Comment by marryton007** [comment]
[nvim-config-2.patch](https://github.com/Martins3/My-Linux-Config/files/10906790/nvim-config-2.patch)

重新改了一下配置，与上一版相比，去掉了一些lsp server，好像没有上面2个问题了。

![image](https://user-images.githubusercontent.com/2311328/223358588-b0a41d0b-ccd8-44a8-a74c-d3bb4fcbe46e.png)

通过结合htop，应该是coc-vimlsp这个有问题

**Comment by Martins3** [comment]
不是吧，coc-vimlsp 是 vimscript 的 lsp，和有关系的可能性应该很小吧

**Comment by Martins3** [comment]
coc-metals : scala 的 lsp 支持，这个可能性大一点

**Comment by marryton007** [comment]
好的，我明天在公司里试一下，只有公司的环境才能复现。

**Comment by Martins3** [comment]
今天我也复现了这个问题，去掉确实消除掉这个错误，看上去是处理软链接的时候有点问题。这个插件以前我是准备看 RISV-V CPU 设计用的，后来不了了之了，下个版本的时候这个插件会去掉。
