### ISSUE TITLE
[coc.nvim] error: TypeError: this.off is not a function  

### ISSUE THREAD

**Issue by maoyanjun** [Martins3/My-Linux-config#3]
- **Describe the bug**

After installing the coc.nvim, and when I start a cpp file with nvim, it will show the error info everytime.

- **ccls --version**
```
ccls version 0.20190823.5-20-g24dd3bd4
clang version 8.0.0 (tags/RELEASE_800/final)
```
- **nvim --version**
```
NVIM v0.5.0-445-gca02db1f9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

```
- **checkhealth screenshot**
```
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5202'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.2.0 (outdated; from /usr/lib/python2.7/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.9
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v8.10.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.


```

- **Error**
```
[coc.nvim] error: TypeError: this.off is not a function                                                                                
    at ServiceManager.listener (/home/maoyanjun/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/lib/services.js:182:26)             
    at emitOne (events.js:121:20)                                                                                                      
    at ServiceManager.emit (events.js:211:7)                                                                                           
    at service.onServiceReady (/home/maoyanjun/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/lib/services.js:73:18)               
    at CallbackList.invoke (/home/maoyanjun/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/node_modules/vscode-jsonrpc/lib/events.j
s:62:39)                                                                                                                               
    at Emitter.fire (/home/maoyanjun/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:121:3
6)                                                                                                                                     
    at client.onReady.then (/home/maoyanjun/.cache/vimfiles/repos/github.com/neoclide/coc.nvim/lib/services.js:296:43)                 
    at <anonymous>
```

**Comment by Martins3** [comment]
I am not the author of coc.nvim and not familiar with Javascript too, here is my attempt at your question:

remove /home/maoyanjun/.cache/vimfiles/repos/github.com/neoclide/ and install coc.nvim again.

the directory, coc.nvim/lib, is generated automatically when building the coc.nvim, so I guess you haven't built the coc.nvim correctly. **To increase the chances of success, please check your npm/yarn mirror**.

**Comment by Martins3** [comment]
1. https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim : how to install coc.nvim with dein
2. https://gitter.im/neoclide/coc-cn?at=5d761a9232e48c5df263589c : a similar problem has already been noticed.

**Comment by Martins3** [comment]
Maybe you have solved the problem. If you have questions, feel free to reopen this issue.
